### ISSUE TITLE
content reference in media

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-media-bundle#167]
I create a content with an image. I change status to published.
I show in mogo an usage reference to content for my media.
In part Media in BO, when i select my media, i can't delete it, one or more usage reference exists. It's normal.
If I delete my content, usage ref to content in media is not deleted. it's always present in mongo, and i can't delete my media.

Version : 1.1.0-alpha4

**Comment by alavieille** [comment]
This is fixed with the possibility to remove an element of trash can.

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1539
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/76
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/189
https://github.com/open-orchestra/open-orchestra-model-interface/pull/172
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/541
